-- 001_init: tables for Hayk's German-learning progress.
--
-- Every table has user_id: the Neon Auth user id (the JWT "sub", neon_auth."user".id as text).
-- Rows are written by the Functions API (backend/src) for the signed-in user, and read or
-- graded by Claude with backend/scripts/progress.py (owner role, server side only).
-- Apply with: uv run backend/scripts/migrate.py apply   (never edit this file after it ran;
-- add 002_*.sql instead, migrate.py refuses a changed checksum).

-- Who may use the API. Neon Auth lets anyone sign up by default, so a valid token alone
-- is not enough: the API answers only users listed here (added by Claude with progress.py).
CREATE TABLE allowed_users (
  user_id  text        PRIMARY KEY,
  email    text        NOT NULL,
  note     text,
  added_at timestamptz NOT NULL DEFAULT now()
);

-- One row per word review, append-only (the old progress/review-log.jsonl).
-- id is generated by the app (crypto.randomUUID()), so a retried sync cannot duplicate a row.
CREATE TABLE review_events (
  user_id      text        NOT NULL,
  id           uuid        NOT NULL,
  ts           timestamptz NOT NULL,                 -- when the card was graded
  local_day    date        NOT NULL,                 -- Hayk's local calendar day at that moment
  time_ms      integer     CHECK (time_ms >= 0),     -- card shown -> graded; NULL only for imported old lines
  word_id      text        NOT NULL,
  de           text        NOT NULL,
  mode         text        NOT NULL CHECK (mode IN ('recognition', 'production', 'listening')),
  rating       smallint    NOT NULL CHECK (rating BETWEEN 1 AND 4),
  answer       text,                                 -- typed modes only
  correct      boolean,                              -- typed modes only
  near_miss    text[]      CHECK (near_miss <@ ARRAY['case', 'umlaut', 'article_missing', 'article_wrong']::text[]),
  is_new       boolean     NOT NULL,
  state_before smallint    NOT NULL CHECK (state_before BETWEEN 0 AND 3),
  state_after  smallint    NOT NULL CHECK (state_after BETWEEN 0 AND 3),
  due          timestamptz NOT NULL,                 -- next review time after this grade
  practice     boolean     NOT NULL DEFAULT false,   -- extra practice of weak words; the schedule was not changed
  received_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, id)
);
CREATE INDEX review_events_user_ts ON review_events (user_id, ts);
CREATE INDEX review_events_user_day ON review_events (user_id, local_day);

-- Current FSRS card per word (the old progress/review-state.json "cards").
-- card is the ts-fsrs StoredCard exactly as the app sends it; due and last_review are copied
-- out of it for queries and for the merge rule (the card with the later last_review wins).
CREATE TABLE review_cards (
  user_id     text        NOT NULL,
  word_id     text        NOT NULL,
  card        jsonb       NOT NULL CHECK (jsonb_typeof(card) = 'object'),
  due         timestamptz NOT NULL,
  last_review timestamptz,
  updated_at  timestamptz NOT NULL DEFAULT now(),   -- server time of the last change
  PRIMARY KEY (user_id, word_id)
);

-- One row per submitted test attempt (the old progress/results/*.json files).
-- items holds the per-item answers and auto-grades exactly as the app sends them.
-- review is Claude's grading (same shape as the "review" key in progress/README.md). The app
-- never sends it; only backend/scripts/progress.py writes it.
CREATE TABLE test_attempts (
  user_id        text        NOT NULL,
  id             uuid        NOT NULL,
  test_id        text        NOT NULL,
  test_title     text        NOT NULL,
  level          text        NOT NULL CHECK (level IN ('A1', 'A2', 'B1', 'B2')),
  mode           text        NOT NULL,
  started_at     timestamptz NOT NULL,
  submitted_at   timestamptz NOT NULL,
  local_day      date        NOT NULL,              -- Hayk's local day at submit time
  lesson_id      text,                              -- set for an exercise inside a lesson ...
  section        integer     CHECK (section >= 0),  -- ... together with the lesson section index
  score          jsonb       NOT NULL CHECK (jsonb_typeof(score) = 'object'),
  items          jsonb       NOT NULL CHECK (jsonb_typeof(items) = 'array'),
  answered_items integer     NOT NULL CHECK (answered_items >= 0),
  review         jsonb       CHECK (
                   review IS NULL
                   OR (jsonb_typeof(review) = 'object'
                       AND review ? 'gradedAt'
                       AND review ? 'summary'
                       AND jsonb_typeof(review -> 'items') = 'array')
                 ),
  reviewed_at    timestamptz,                       -- when progress.py wrote the review
  received_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, id),
  CHECK (submitted_at >= started_at),
  CHECK (answered_items <= jsonb_array_length(items)),
  CHECK ((review IS NULL) = (reviewed_at IS NULL)),
  CHECK ((lesson_id IS NULL) = (section IS NULL))
);
CREATE INDEX test_attempts_user_submitted ON test_attempts (user_id, submitted_at DESC);
CREATE INDEX test_attempts_ungraded ON test_attempts (user_id, submitted_at) WHERE review IS NULL;

-- Which lessons were started and done, and where Hayk was in each (the app's LessonProgress,
-- the old progress/lessons.json). The record with the later updated_at wins.
CREATE TABLE lesson_progress (
  user_id      text        NOT NULL,
  lesson_id    text        NOT NULL,
  started_at   timestamptz NOT NULL,
  updated_at   timestamptz NOT NULL,                -- app time of the last change (the merge key)
  last_section integer     NOT NULL CHECK (last_section >= 0),
  done_at      timestamptz,
  received_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, lesson_id)
);

-- Extra new words Hayk asked for on a day ("learn more"; ReviewState.newToday.extra).
-- It only grows during a day, so two devices merge by taking the larger value.
CREATE TABLE new_word_extras (
  user_id    text        NOT NULL,
  local_day  date        NOT NULL,
  extra      integer     NOT NULL CHECK (extra >= 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, local_day)
);
